### ISSUE TITLE
Completions not working at all

### ISSUE THREAD

**Issue by siduck** [xna00/unocss-language-server#8]
hi @xna00 , i have used this lsp before and it worked fine but now the completions dont show up

![image](https://github.com/xna00/unocss-language-server/assets/59060246/ccbb71ed-4449-4fcf-a1fa-668539761fd3)
![image](https://github.com/xna00/unocss-language-server/assets/59060246/242819bd-bd9a-4446-acdf-b2e70579cbde)

Also i do have the trigger_chars* setup in my cmp config too

**Comment by Jason-Jay-Mason** [comment]
@xna00, thanks for taking the time to build this for the community.

@siduck, It seems like @xna00 may be inactive at the time. In the mean time, I branched this and updated the packages. And everything seems to work:

[https://github.com/Jason-Jay-Mason/unocss-language-server.git](url)

Let me know if you need any help beyond that.

**Comment by siduck** [comment]
> @xna00, thanks for taking the time to build this for the community.
> 
> @siduck, It seems like @xna00 may be inactive at the time. In the mean time, I branched this and updated the packages. And everything seems to work:
> 
> [https://github.com/Jason-Jay-Mason/unocss-language-server.git](url)
> 
> Let me know if you need any help beyond that.

hmm how am I supposed to install your version? same package name?

**Comment by Jason-Jay-Mason** [comment]
I don't have it on npm, because I want to avoid creating a competing implementation as I think a standard lsp for Uno is something that should ideally be offered by Unocss. Especially since this repo seems to be more of a shell while most of the actual implementation is being handled by @unocss/autocomplete. Anyways... you can clone my fork then:

```bash
# navigate to the project in your console
cd /path/to/unocss-language-server
# run the build script
pnpm build
# link it globally
npm link
```
So that is building the project and linking it for global use via npm. This may work for you. Now, I had to also fix a dependency of @unocss/autocomlete: "fzf". I had to locate fzf in node_modules and delete "type:module" in its package.json. So you might need to do this too.

Also, it seems your using neovim, so make sure you are instantiating the lsp (assuming your using lspconfig):
```lua
-- ...somewhere inside your nvim config
local config = require('lspconfig')
config.unocss.setup {}
```
A bit hacky for now, but unocss is new, the tooling will get there with time and contributions from the community.

**Comment by siduck** [comment]
ugh  the 2nd step seems like a bad workaround :sob:

**Comment by Jason-Jay-Mason** [comment]
Right @siduck, I agree, but it's all I have for ya. Let me know if you find something better!  When I get time, I may look at contributing to unocss to help get a core lsp implementation going, that feels like the right move instead of maintaining a separate wrapper like this. Best of luck.

**Comment by javlocan** [comment]
Hey! Sorry if anything I ask here is too basic. I'm assuming some stuff and I might be wrong, my experience as a developer is limited. I'm also using Nvim.

I followed your instructions (cloned, installed** and linked to global npm). Couldn't find "type:module" or any variant I could think off in reference or my npm global directory. Could you help me? Last week I'm sure I was able to use this even with Attributify (that's my goal)

Thanks for taking the time.

**Comment by carere** [comment]
@javlocan you need to go the `node_modules` folder inside `unocss-language-server`, and then locate the `fzf` folder and inside the `package.json`, you need to remove the line `"type": "module"`.
@Jason-Jay-Mason thx for your fork, I'm using it and it works like a charm, I'll try to update the code in order to provide a `classRegexp` like feature like with TailwindCss Configuration :)

**Comment by carere** [comment]
You should clone the https://github.com/Jason-Jay-Mason/unocss-language-server repo, then `npm i` / `pnpm i` inside the repo, then, in the `node_modules` folder generated, you should find the fzf folder, and follow as I explained on my previous message.

**Comment by h4rldev** [comment]
Hello, uhh there's no fzf folder generated

**Comment by RayGuo-ergou** [comment]
> Hello, uhh there's no fzf folder generated

If you install with `pnpm` it's in `node_modules/.pnpm`

**Comment by NDK2020** [comment]
Hi,

I can't get autocompletion to work in  Nuxt version 3.11.1

I get this error of LSP when open a file vue:

Client 2 quit with exit code 1 and signal 0

```
LspInfo

 Other clients that match the filetype: vue
 
 Config: unocss
 	filetypes:         vue
 	root directory:    /home/user/work/dev/learn.nuxt.com
 	cmd:               /home/user/.local/share/nvim/mason/bin/unocss-language-server --stdio
 	cmd is executable: true
 	autostart:         true
 	custom handlers:   
```

I follow suggestion of @Jason-Jay-Mason, also delete `type:modules` and it still get the same error.

**Comment by siduck** [comment]
i can confirm that completions work now, to everyone else facing this issue, make sure node_modules are installed
